import socket
import struct

header = "# Generated by iptables-save v1.4.21 on Sat Mar 10 22:08:32 2018\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n"
count = 2000000
random_ip = 168430090

filter_begin = "-A INPUT -s "
filter_end = " -j DROP\n"

fh = open("iptable_conf","w")
fh.write(header)


for i in range(0,count):
	ip_gen = i + random_ip
	filter = filter_begin + socket.inet_ntoa(struct.pack("!I", ip_gen)) + filter_end
	fh.write(filter)

fh.write("COMMIT\n")
fh.write("# Completed on Sat Mar 10 22:08:32 2018\n")
fh.close()